/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: emran.bayati (https://sketchfab.com/emran.bayati)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jersey-barrier-b52246c9611a42a99a03b425535a0237
Title: Jersey Barrier
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Barrier(props) {
  const { nodes, materials } = useGLTF('/models/barrier2.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.NewJersey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.NewJersey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.NewJersey}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/barrier2.glb')

export default Barrier;

