/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2018-hyundai-i30-n-c85b558abbd14acab590f92be22423a4
Title: 2018 Hyundai i30 N
*/

import React, { useRef } from 'react'
import gsap from 'gsap';
import { useEffect } from 'react';
import { useGSAP } from '@gsap/react';
import { useGLTF } from '@react-three/drei'

export function Vehicle({type=1,...props}) {

  const { nodes, materials } = useGLTF('/models/vehicleHyundai.glb')
  
  const hyundaiVehicle = useRef();

  // // GSAP animation
  // useEffect(() => {
  //   if (hyundaiVehicle.current) {
  //     gsap.to(hyundaiVehicle.current.position, {
  //       z: 2, // Move the vehicle along the Z-axis
  //       duration: 2.5,
  //       ease: "power2.inOut",
  //     });
  //   }
  // }, []); // Runs once when the component mounts

  useGSAP(() => {
    gsap
      .timeline({
        repeat: -1,
        repeatDelay: 0.5,
      })
      .to(hyundaiVehicle.current.position,{
        z:-1,
        x: type === 1 ? -4.5 : -1,
        duration: 2,
        yoyo:true, //this gives it the yoyo effect -> it goes up and down
        repeat:-1
      })
  })

  
  return (
    <group {...props} ref ={hyundaiVehicle} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .HWheelFL_TiresWheelFLbone_wheel_FL_rotationbone_wheel_FL_steercar_hyundai_i30n_Hphong7SG1_0
              .geometry
          }
          material={materials.Hphong7SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hcar_hyundai_i30nchassis_Bottomchassis_Hphong6SG1_0.geometry}
          material={materials.Hphong6SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nlights_reverse_pivot_Glowslights_reverse_pivotlights_reverse_Hphong1SG1_0
              .geometry
          }
          material={materials.Hphong1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nlights_brakes_pivot_Glowslights_brakes_pivotlights_brakes_Hphong2SG1_0
              .geometry
          }
          material={materials.Hphong2SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hcar_hyundai_i30nchassischassis_Details_Hphong1SG1_0.geometry}
          material={materials.Hphong1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hcar_hyundai_i30nchassischassis_licenseplate_Hphong5SG1_0.geometry}
          material={materials.Hphong5SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nWheelBL_TiresWheelBLbone_wheel_BL_rotationbone_wheel_BL_steer_Hphong7SG1_0
              .geometry
          }
          material={materials.Hphong7SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nlights_position_back_pivot_Glowslights_position_back_pivotlights_position_back_Hphong3SG1_0
              .geometry
          }
          material={materials.Hphong3SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Hcar_hyundai_i30nglasses_pivot_Glass_Lightsglasses_pivotglasses_Hphong2SG1_0
              .geometry
          }
          material={materials.Hphong2SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Hcar_hyundai_i30ndetach_door_R_70_Carpaintdetach_door_R_70_Hphong4SG1_0.geometry
          }
          material={materials.Hphong4SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Hcar_hyundai_i30ndetach_door_R_70_Carpaintdetach_door_R_70_carpaint_0.geometry
          }
          material={materials.carpaint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30ndetach_door_L_70_pivot_Carpaintdetach_door_L_70_pivotdetach_door_L_70_Hphong4SG1_0
              .geometry
          }
          material={materials.Hphong4SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30ndetach_door_L_70_pivot_Carpaintdetach_door_L_70_pivotdetach_door_L_70_carpaint_0
              .geometry
          }
          material={materials.carpaint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nbone_caliper_BR_Rimsbone_caliper_BRbone_wheel_BR_steer_Hphong1SG1_0
              .geometry
          }
          material={materials.Hphong1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .HWheelFLbone_wheel_FL_rotationbone_wheel_FL_steercar_hyundai_i30nWheelFL_Rims_Hphong1SG1_0
              .geometry
          }
          material={materials.Hphong1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30ndetach_door_L_70_pivotdetach_door_L_70detach_door_L_70_pivot_Plastic_Hphong4SG1_0
              .geometry
          }
          material={materials.Hphong4SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nWheelFR_RimsWheelFRbone_wheel_FR_rotationbone_wheel_FR_steer_Hphong1SG1_0
              .geometry
          }
          material={materials.Hphong1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nbone_wheel_BR_steerWheelBR_RimsWheelBRbone_wheel_BR_rotation_Hphong1SG1_0
              .geometry
          }
          material={materials.Hphong1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nbone_wheel_FR_steerbone_caliper_FR_Rimsbone_caliper_FR_Hphong1SG1_0
              .geometry
          }
          material={materials.Hphong1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hcar_hyundai_i30nchassischassis_Plastic_Hphong4SG1_0.geometry}
          material={materials.Hphong4SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nWheelFRbone_wheel_FR_rotationbone_wheel_FR_steerWheelFR_Tires_Hphong7SG1_0
              .geometry
          }
          material={materials.Hphong7SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hcar_hyundai_i30nchassischassis_Chrome_Hphong1SG1_0.geometry}
          material={materials.Hphong1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Hcar_hyundai_i30ndetach_door_R_70detach_door_R_70_Plastic_Hphong4SG1_0.geometry
          }
          material={materials.Hphong4SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nWheelBLbone_wheel_BL_rotationbone_wheel_BL_steerWheelBL_Rims_Hphong1SG1_0
              .geometry
          }
          material={materials.Hphong1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nbone_wheel_BR_steerWheelBRbone_wheel_BR_rotationWheelBR_Tires_Hphong7SG1_0
              .geometry
          }
          material={materials.Hphong7SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Hcar_hyundai_i30nglasses_pivotglassesglasses_pivot_Glass_Hphong2SG1_0.geometry
          }
          material={materials.Hphong2SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hbone_wheel_FL_steercar_hyundai_i30nbone_caliper_FL_Rimsbone_caliper_FL_Hphong1SG1_0
              .geometry
          }
          material={materials.Hphong1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30nbone_wheel_BL_steerbone_caliper_BL_Rimsbone_caliper_BL_Hphong1SG1_0
              .geometry
          }
          material={materials.Hphong1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30ndetach_hood_45_pivot_Carpaintdetach_hood_45_pivotdetach_hood_45_Hphong4SG1_0
              .geometry
          }
          material={materials.Hphong4SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .Hcar_hyundai_i30ndetach_hood_45_pivot_Carpaintdetach_hood_45_pivotdetach_hood_45_carpaint_0
              .geometry
          }
          material={materials.carpaint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hcar_hyundai_i30nchassischassis_Carpaint_Hphong4SG1_0.geometry}
          material={materials.Hphong4SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hcar_hyundai_i30nchassischassis_Carpaint_carpaint_0.geometry}
          material={materials.carpaint}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/vehicleHyundai.glb')

export default Vehicle;
