/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: RaduCarstean (https://sketchfab.com/RaduCarstean)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/hellhole-soldier-model-37f49032ba544088bd1f1cb7c4b7e179
Title: Hellhole - Soldier Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shooter(props) {
  const { nodes, materials } = useGLTF('/models/military/shooter.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[4.306, 0, 24.267]} scale={[1.285, 1, 1.492]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube2_lambert14_0.geometry}
          material={materials.lambert14}
          position={[8.901, -4.147, -4.556]}
          scale={[26.223, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube5_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-28.644, -4.147, -15.811]}
          rotation={[-0.027, 0.026, -0.019]}
          scale={[22.957, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube4_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-18.122, -4.147, -27.534]}
          rotation={[0, -0.031, 0]}
          scale={[26.223, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube6_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-31.42, -4.147, 6.776]}
          scale={[26.223, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube3_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-43.726, -4.147, -27.441]}
          rotation={[-0.006, 0.018, 0.006]}
          scale={[22.401, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube7_lambert14_0.geometry}
          material={materials.lambert14}
          position={[18.98, -4.147, 6.845]}
          scale={[16.626, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube8_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-18.122, -4.147, -4.5]}
          rotation={[-0.025, 0.039, -3.105]}
          scale={[23.161, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube11_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-17.224, -4.147, 18.351]}
          scale={[13.355, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube12_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-42.653, -4.147, -4.5]}
          scale={[23.552, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube14_lambert14_0.geometry}
          material={materials.lambert14}
          position={[4.402, -4.147, -27.143]}
          rotation={[-0.027, -0.02, -0.02]}
          scale={[17.054, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube15_lambert14_0.geometry}
          material={materials.lambert14}
          position={[22.728, -4.147, -15.832]}
          rotation={[-0.025, 0.007, -3.106]}
          scale={[18.721, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube16_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-3.031, -4.147, -38.419]}
          rotation={[-0.006, 0.018, 0.006]}
          scale={[26.223, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube19_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-27.237, -4.147, -39.103]}
          rotation={[-0.02, -0.06, -0.031]}
          scale={[19.207, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube20_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-18.122, -4.147, -50.175]}
          rotation={[-0.03, 0.007, 0.032]}
          scale={[23.419, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube21_lambert14_0.geometry}
          material={materials.lambert14}
          position={[11.211, -4.147, -49.988]}
          rotation={[-0.02, -0.06, -0.031]}
          scale={[26.223, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube22_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-5.603, -4.147, -61.984]}
          rotation={[0, 0.05, 0]}
          scale={[15.253, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube23_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-4.339, -4.147, -15.832]}
          scale={[22.201, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube24_lambert14_0.geometry}
          material={materials.lambert14}
          position={[-3.031, -4.147, 7.018]}
          rotation={[-0.04, 0.024, 0.039]}
          scale={[26.223, 7.83, 10.981]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube25_lambert14_0.geometry}
          material={materials.lambert14}
          position={[3.585, -4.147, 18.295]}
          rotation={[-0.013, 0.028, 0.005]}
          scale={[26.223, 7.83, 10.981]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Pouch_chest_2_lambert20_0.geometry}
        material={materials.lambert20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Pouch_chest_1_lambert20_0.geometry}
        material={materials.lambert20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Pouch_chest_3_lambert21_0.geometry}
        material={materials.lambert21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Pouch_waist_3_lambert18_0.geometry}
        material={materials.lambert18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Magazine_1_lambert18_0.geometry}
        material={materials.lambert18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Bullet_Case_2_lambert18_0.geometry}
        material={materials.lambert18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Pouch_waist_2_lambert18_0.geometry}
        material={materials.lambert18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Magazine_3_lambert18_0.geometry}
        material={materials.lambert18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Bullet_Case_3_lambert18_0.geometry}
        material={materials.lambert18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Pouch_waist_1_lambert18_0.geometry}
        material={materials.lambert18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Magazine_2_lambert18_0.geometry}
        material={materials.lambert18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Bullet_Case_1_lambert18_0.geometry}
        material={materials.lambert18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Pouch_waist_R_1_lambert19_0.geometry}
        material={materials.lambert19}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Pouch_waist_L_1_lambert19_0.geometry}
        material={materials.lambert19}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Backpack_lambert15_0.geometry}
        material={materials.lambert15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Body_lambert17_0.geometry}
        material={materials.lambert17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Body_lambert24_0.geometry}
        material={materials.lambert24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_Body_lambert16_0.geometry}
        material={materials.lambert16}
      />
      <group position={[-18.889, 98.28, 35.695]} rotation={[0.344, 0.143, -0.111]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SAIGA_Gun_Body1_lambert22_0.geometry}
          material={materials.lambert22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SAIGA_Fire_Selector_lambert22_0.geometry}
          material={materials.lambert22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SAIGA_Bolt_Carrier_lambert22_0.geometry}
          material={materials.lambert22}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SAIGA_Magazine_lambert23_0.geometry}
        material={materials.lambert23}
        position={[-18.889, 98.28, 35.695]}
        rotation={[0.344, 0.143, -0.111]}
      />
    </group>
  )
}

useGLTF.preload('/models/military/shooter.glb')

export default Shooter;