/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Opus Poly (https://sketchfab.com/OpusPoly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gislinge-viking-boat-01098ad7973647a9b558f41d2ebc5193
Title: Gislinge Viking Boat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

export function Boat(props) {
    const { nodes, materials } = useGLTF('/models/ocean/boat.glb')

    const boat = useRef()
    useGSAP(() => {
        gsap
          .timeline({
            repeat: -1,
            repeatDelay: 0.5,
          })
          .to(boat.current.position,{
            y:0.5,
            duration: 1,
            yoyo:true, //this gives it the yoyo effect -> it goes up and down
            repeat:-1
          })
      })


  return (
    <group {...props} dispose={null} ref={boat}> 
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rigging_Pin_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
        position={[-73.647, 62.374, 83.811]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rigging_Pin001_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
        position={[72.429, 62.374, -151.984]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rigging_Pin002_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
        position={[-72.66, 62.374, -151.984]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sail_Full_Sail_Full_0.geometry}
        material={materials.Sail_Full}
        position={[4.14, 420.924, 12.833]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sail_Ropes_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
        position={[4.14, 420.924, 12.833]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Yard_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
        position={[0, 425, 6.355]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Yard_Rope_Raised_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
        position={[6.189, 95.831, 6.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mast_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
        position={[0, 18.506, 6.355]}
        rotation={[0, 1.484, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shrouds_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stay_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
        position={[0, 92.012, 334.647]}
        rotation={[-0.729, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Yard_Rope_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
        position={[-6.632, 38.041, -73.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keel_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stems_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Planking_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frames_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stanchions_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rudder_Frame_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stringer_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thole_Straps_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rudder_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
        position={[-30.279, 68.369, -325.946]}
        rotation={[0.37, 0.079, 0.257]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tiller_Ship_Oak_Aged_0.geometry}
        material={materials.Ship_Oak_Aged}
        position={[-2.408, 105.155, -311.127]}
        rotation={[0.28, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/ocean/boat.glb')

export default Boat;