/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cyborg-cop-7a7ed988d149408ebe198c21f8040939
Title: Cyborg Cop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cyborg(props) {
  const { nodes, materials } = useGLTF('/models/military/cyborg.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.414, 1.358, 0.622]} rotation={[1.661, -0.199, 0.386]} scale={0.023}>
        <group position={[0, 0.082, 0.157]} rotation={[0.32, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_7.geometry}
            material={materials.pistol1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_9.geometry}
            material={materials.pistol1}
            position={[0, 0.089, -3.186]}
            rotation={[-0.614, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_11.geometry}
            material={materials.pistol1}
            position={[-0.279, -1.559, -5.997]}
            rotation={[-0.534, -0.017, -0.578]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_13.geometry}
            material={materials.pistol1}
            position={[-0.717, -4.114, -8.552]}
            rotation={[2.398, 0.761, -1.267]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_15.geometry}
            material={materials.pistol1}
            position={[-0.607, -2.824, -7.339]}
            rotation={[0.192, -0.601, 1.285]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_17.geometry}
            material={materials.pistol1}
            position={[-0.143, -0.535, -4.77]}
            rotation={[2.069, 0.948, -2.455]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_19.geometry}
            material={materials.pistol1}
            position={[-1.262, -5.578, -9.806]}
            rotation={[-0.497, 0.801, -0.916]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.pistol1}
          position={[0, -0.212, 0.222]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.pistol1}
          position={[0, -0.492, -3.137]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.pistol1}
          position={[0, 2.621, -2.067]}
          rotation={[0.349, 0, 0]}
        />
      </group>
      <group position={[0, 0, -0.007]}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_28.geometry}
          material={materials.Body}
          skeleton={nodes.Object_28.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_29.geometry}
          material={materials.headgear}
          skeleton={nodes.Object_29.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_30.geometry}
          material={materials.gear}
          skeleton={nodes.Object_30.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_31.geometry}
          material={materials.Gear_2}
          skeleton={nodes.Object_31.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_32.geometry}
          material={materials.Vest_and_Belt}
          skeleton={nodes.Object_32.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_33.geometry}
          material={materials.Hood}
          skeleton={nodes.Object_33.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_34.geometry}
          material={materials.Boot}
          skeleton={nodes.Object_34.skeleton}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_101.geometry}
        material={materials.muzzle_flashes}
        position={[-0.512, 1.423, 0.908]}
        rotation={[0, -0.658, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/military/cyborg.glb')


export default Cyborg;