/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lukas Bobor (https://sketchfab.com/LukasBobor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dead-body-fdfca2c19a784789804f39d24f25bd8c
Title: Dead Body
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bed(props) {
  const { nodes, materials } = useGLTF('/models/hospital/dead_body.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          name="defaultMaterial"
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial.geometry}
          material={materials.DefaultMaterial}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/hospital/dead_body.glb')
export default Bed