/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: GLTFconverter (https://sketchfab.com/GLTFconverter)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/new-ezzet-sleeping-mri-6e3d9689abb94eab8a924530260a9ad6
Title: New_ezzet_sleeping_MRI
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DeadGirl(props) {
  const { nodes, materials } = useGLTF('/models/hospital/deadgirl.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedCC_Base_Body_ezzet_optimisedStd_Skin_Head1_0.geometry}
          material={materials.ezzet_optimisedStd_Skin_Head1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedCC_Base_Body_ezzet_optimisedStd_Skin_Body1_0.geometry}
          material={materials.ezzet_optimisedStd_Skin_Body1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedCC_Base_Body_ezzet_optimisedStd_Skin_Arm1_0.geometry}
          material={materials.ezzet_optimisedStd_Skin_Arm1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedCC_Base_Body_ezzet_optimisedStd_Nails1_0.geometry}
          material={materials.ezzet_optimisedStd_Nails1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedBoots_ezzet_optimisedBoots1_0.geometry}
          material={materials.ezzet_optimisedBoots1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedCC_Base_Eye_ezzet_optimisedStd_Eye_R1_0.geometry}
          material={materials.ezzet_optimisedStd_Eye_R1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedCC_Base_Eye_ezzet_optimisedStd_Eye_L1_0.geometry}
          material={materials.ezzet_optimisedStd_Eye_L1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedShirt_ezzet_optimisedShirt1_0.geometry}
          material={materials.ezzet_optimisedShirt1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedJeans_ezzet_optimisedJeans1_0.geometry}
          material={materials.ezzet_optimisedJeans1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedHair_ezzet_optimisedskullcap1_0.geometry}
          material={materials.ezzet_optimisedskullcap1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedHair_ezzet_optimisedupper1_0.geometry}
          material={materials.ezzet_optimisedupper1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ezzet_optimisedHair_ezzet_optimisedlower1_0.geometry}
          material={materials.ezzet_optimisedlower1}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/hospital/deadgirl.glb')

export default DeadGirl

