/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aaden (https://sketchfab.com/aadenhelan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-computer-desk-7ae65baca1ed448a885a40dcfa7ab1d0
Title: Wooden Computer Desk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Desk(props) {
  const { nodes, materials } = useGLTF('/models/hospital/desk.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.597}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_0.geometry}
          material={materials.Material}
          position={[-1.577, 0.756, 0.765]}
          scale={[-0.046, 0.049, 0.826]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_0.geometry}
          material={materials.Material}
          position={[1.574, 0.756, 0.765]}
          scale={[-0.046, 0.049, 0.826]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_0.geometry}
          material={materials.Material}
          position={[1.574, -0.754, 0.765]}
          scale={[-0.046, 0.049, 0.826]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_0.geometry}
          material={materials['Cylinder.002_0']}
          position={[-0.381, -0.004, 1.446]}
          scale={[-0.022, 0.731, 0.049]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_0.geometry}
          material={materials.Material}
          position={[0.003, 0.003, 1.609]}
          scale={[1.066, 1.041, 0.952]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_0.geometry}
          material={materials.Material}
          position={[0.003, 0, 1.51]}
          scale={[1.575, 0.781, 0.083]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_0.geometry}
          material={materials['Cylinder.002_0']}
          position={[0.336, -0.004, 1.447]}
          scale={[-0.022, 0.731, 0.048]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_0.geometry}
          material={materials.Material}
          position={[-1.554, -0.754, 0.765]}
          scale={[-0.046, 0.049, 0.826]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0.geometry}
          material={materials['Material.002']}
          position={[0.017, -0.803, 1.54]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_0.geometry}
          material={materials['Material.002']}
          position={[0.016, -0.804, 1.508]}
          rotation={[-1.532, 0, 0]}
          scale={[0.002, 0.002, 0.006]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_0.geometry}
          material={materials['Cylinder.002_0']}
          position={[0.016, -0.81, 1.504]}
          rotation={[-1.53, 0, 0]}
          scale={[-0.004, 0.004, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/hospital/desk.glb')

export default Desk